application: !factory:hjudge_ui.application.Application
  decorators: !ref:decorators

decorators:
  - !factory:hjudge_ui.application.UiDecorator
  - !factory:hjudge_ui.application.BootstrapDecorator
  - !factory:hjudge_ui.application.ApiDecorator
      handler: !factory:hjudge_ui.echo_handler.EchoHandler

